"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard from './dashboard.bones.json'

configureBoneyard({"color":"rgba(255,255,255,0.04)","darkColor":"rgba(255,255,255,0.04)","animate":"pulse"})

registerBones({
  "dashboard": _dashboard,
})
